Remove dependency on vtk/libproj-dev
ros-perception/perception_pcl pull request #145
Opened 2017-05-10 16:25 UTC by wkentaro

> These dependencies were introduced in #124 to temporarily fix
> missing / wrong dependencies in upstream vtk. This hack is no longer
> necessary, since fixed vtk packages have been uploaded to
> packages.ros.org (see #124 and ros-infrastructure/reprepro-updater#32).

Close #126

2017-05-11 18:19 UTC, paulbovbel commented
that makes a lot of sense!

2017-05-11 18:19 UTC, paulbovbel approved these changes

2017-05-11 18:21 UTC, paulbovbel requested changes

2017-05-11 18:21 UTC, paulbovbel commented on pcl_ros/package.xml
> -  <depend>libvtk-java</depend>
Can we remove these hacks now as well?

https://github.com/ros-perception/perception_pcl/blob/lunar-devel/pcl_ros/CMakeLists.txt#L12

2017-05-12 03:44 UTC, wkentaro commented on pcl_ros/package.xml
> -  <depend>libvtk-java</depend>
I found it works.

2017-05-12 06:23 UTC, mikaelarguedas commented
that's pretty awesome, if it works it may be worth trying to also revert the Qt5 hacks from #140 and #141 ? (because I believe the Qt5 errors on stretch came from `vtk-java` in the first place)

2017-05-13 11:27 UTC, wkentaro commented
> that's pretty awesome, if it works it may be worth trying to also revert the Qt5 hacks from #140 and #141 ? (because I believe the Qt5 errors on stretch came from vtk-java in the first place)

It fails actually: https://github.com/ros-perception/perception_pcl/pull/146

2017-05-13 19:35 UTC, mikaelarguedas commented
> It fails actually: #146

too bad, thanks for trying it out!

2017-05-14 03:42 UTC, paulbovbel approved these changes

2017-05-14 03:57 UTC, merged