Add samples and tests
ros-perception/perception_pcl pull request #147
Opened 2017-05-30 17:49 UTC by wkentaro

## Why?

To quickly understand the feature of each node.

## NodeLets

- statistical_outlier_removal
- voxel_grid

2017-08-07 14:33 UTC, paulbovbel requested changes

2017-08-07 14:33 UTC, paulbovbel commented on pcl_ros/CMakeLists.txt
> +catkin_download(table_scene_lms400.pcd http://download.ros.org/data/pcl/table_scene_lms400.pcd
if these are for testing purposes only, then move it to the testing if block, that way the file doesn't get downloaded during normal builds

2017-08-07 15:11 UTC, wkentaro commented on pcl_ros/CMakeLists.txt
> +catkin_download(table_scene_lms400.pcd http://download.ros.org/data/pcl/table_scene_lms400.pcd
This data is also used to run the sample, which works only if this package is installed from source.
So I need to write this line here.

2017-08-07 16:14 UTC, paulbovbel approved these changes
Fair enough. Thanks for the addition, apologies for the delay.

2017-08-08 18:55 UTC, wkentaro commented
Thanks for the review.

2017-08-08 18:55 UTC, merged