use <chrono> and <thread> on Windows
ros-perception/perception_pcl pull request #221
Opened 2019-02-01 22:51 UTC by kejxu

`usleep` is only available on Linux, use `this_thread::sleep_for` from STL on Windows to work around the issue

2019-02-02 00:03 UTC, kejxu commented
this change is only limited to Windows build environment, should not affect Linux build result

2019-03-07 23:03 UTC, seanyen-msft commented
@paulbovbel @wkentaro  Hope I am pinging the correct maintainers. We'd love some feedbacks and see how we can make this fix back to the upstream. Thanks! (BTW, this is verified in http://aka.ms/ros project.)

2019-03-08 00:41 UTC, LucidOne requested changes
Melodic targets C++14 so I don't think this actually needs to be `#ifdef`ed
http://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023
http://wiki.ros.org/melodic/Migration

It isn't a blocker to me for this, but if windows specific PRs are landing, I'd like to see a PR fior Travis to handle windows builds.

2019-03-15 16:29 UTC, kejxu commented
> Melodic targets C++14 so I don't think this actually needs to be `#ifdef`ed

My apologies for the delay, and thanks a ton for pointing this out! I have removed the Windows-specific guard.
 
> It isn't a blocker to me for this, but if windows specific PRs are landing, I'd like to see a PR for Travis to handle windows builds.

at this point we are having a [daily build](https://ros-win.visualstudio.com/ros-win/_build?definitionId=19
) to verify Windows build quality. We are still working on an Azure-Pipelines-based pull request builder solution, and we will propose corresponding change when that is finished =)

2019-03-15 17:12 UTC, kejxu commented
travis builds successfully for melodic, fails for kinetic builds

2019-03-27 17:43 UTC, kejxu commented
just a friendly ping @LucidOne =), any update on this?

2019-03-27 22:06 UTC, LucidOne commented
I'm good with merging this unless @paulbovbel  has any  feedback. I was just hoping to check on the failed tests first. If it isn't merged by Monday ping me again.

2019-04-01 20:05 UTC, kejxu commented
@LucidOne my apologies for the spam, but let me just send out this friendly ping again =)

2019-04-05 14:41 UTC, LucidOne approved these changes

2019-04-05 14:50 UTC, merged

2019-04-05 14:50 UTC, LucidOne commented
Thanks for your patience. I should have builds working again soon. I think it's an issue with rosdep network connection timing out.

2019-04-05 17:32 UTC, kejxu commented
> Thanks for your patience. I should have builds working again soon. I think it's an issue with rosdep network connection timing out.

No worries, thanks a lot for revisiting this! Hopefully the build would get fixed soon =)